### ISSUE TITLE
error with mysql syntax

### ISSUE THREAD

**Issue by frank3427** [creatif-studio/ansible-mariadb#5]
has anyone else had this issue?  with these two tasks, looking for  a resolution
TASK [Config Replication[Server 0]] ************************************************************************************
skipping: [192.168.10.72]
fatal: [192.168.10.71]: FAILED! => {"changed": false, "msg": "(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'changed': True, 'stdout': '192.168.10.72', 'stderr': '', 'rc': 0, 'cmd': ['ec...' at line 1\"). Query == CHANGE MASTER TO [\"MASTER_HOST='{'changed': True, 'stdout': '192.168.10.72', 'stderr': '', 'rc': 0, 'cmd': ['echo', '192.168.10.72'], 'start': '2023-02-18 22:31:43.417981', 'end': '2023-02-18 22:31:43.429498', 'delta': '0:00:00.011517', 'msg': '', 'stdout_lines': ['192.168.10.72'], 'stderr_lines': [], 'failed': False}'\", \"MASTER_USER='********'\", \"MASTER_PASSWORD='********'\", \"MASTER_LOG_FILE='mysql-bin.000006'\", 'MASTER_LOG_POS=328']"}

TASK [Config Replication[Server 1]] ************************************************************************************
fatal: [192.168.10.72]: FAILED! => {"changed": false, "msg": "(1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'changed': True, 'stdout': '192.168.10.71', 'stderr': '', 'rc': 0, 'cmd': ['ec...' at line 1\"). Query == CHANGE MASTER TO [\"MASTER_HOST='{'changed': True, 'stdout': '192.168.10.71', 'stderr': '', 'rc': 0, 'cmd': ['echo', '192.168.10.71'], 'start': '2023-02-18 22:31:43.408348', 'end': '2023-02-18 22:31:43.420107', 'delta': '0:00:00.011759', 'msg': '', 'stdout_lines': ['192.168.10.71'], 'stderr_lines': [], 'failed': False}'\", \"MASTER_USER='********'\", \"MASTER_PASSWORD='********'\", \"MASTER_LOG_FILE='mysql-bin.000005'\", 'MASTER_LOG_POS=328']"}

**Comment by yuuzukatsu** [comment]
Hello thank you for submitting issue
I checked this is because i missed .stdout in "Config Replication" 
`primary_host : "{{ hostvars[groups['master'].1].master_host }}"`
should have been 
`primary_host : "{{ hostvars[groups['master'].1].master_host.stdout }}"`
I have pushed a fix 
[https://github.com/sgnd/mysql-installer/commit/a9211549f3b55c00a276252731e4b9e8cd1c4e56](url)

thanks !

**Comment by frank3427** [comment]
thank you for the update, I will try using your changes. I was also able to resolve my issue with following
primary_host: "{{ hostvars[groups['master'].1].inventory_hostname }}"
